name: Wanga Theme
markdown: redcarpet
pygments: true

permalink: /:year/:month/:title/
owner:
    name: Nii Adjetey Sowah
    twitter: #
    github: #
    disqus_shortname: #
    
ga_id: #
ga_username: #
        